# site properties and page defaults
title: Stajich Laboratory for Fungal Evolutionary Genomics
description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
logo: images/logo.svg
header: images/backgrounds/mojave_cholla_background.jpg
footer: images/backgrounds/mojave_cholla_background.jpg
baseurl: /

# site social media and other links
links:
  email: jason.stajich@ucr.edu
  google-scholar: t_YIP5UAAAAJ
  github: stajichlab
  twitter: stajichlab
  instagram: stajichlab
  youtube: stajichlab
  orcid: 0000-0002-7591-0020

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata
  # - jekyll-avatar
  - jekyll-gist
  - jekyll-mentions
  - jekyll-relative-links
    #- jemoji

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
